server:
  port: 9001

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
#    ec2 cosmost-db ip
#    url: jdbc:mysql://3.38.146.80:3306/cosmost
    url: jdbc:mysql://localhost:3306/cosmost_db
    password: 1234
  redis:
#    host: 127.0.0.1
    host: cosmost-auth.wzgk6w.ng.0001.apn2.cache.amazonaws.com
    password: '1234'
    port: 6379
    session:
      store-type: redis

#    ec2 cosmost-db ip
#    url: jdbc:mysql://3.38.146.80:3306/cosmost
#    password: '1234'
  redis:
    host: 127.0.0.1
    password: 1234ffd
    port: 6379
    session:
      store-type: redis

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: false

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    hiddenmethod:
      filter:
        enabled: 'true'

  profiles:
<<<<<<< Updated upstream
    include: email, redis
=======
    include: email, aws
>>>>>>> Stashed changes

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error

jwt:
  tokenValidTime: 18000000000000
  secret: COS-MOST-TEAM-SECRET-KEY