spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: olOWHLuaPPHW2uZwF5H4
            client-secret: xVq5RFhQgV
#            redirect-uri: http://localhost:9001/v1/signin/naver
#            redirect-uri: http://localhost:9001/login/v1/signin/naver
            redirect-uri: http://localhost:9001/login/oauth2/code/social
            authorization-grant-type: authorization_code
            scope: email, nickname, profile_image, age
            client-name: Naver
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response