mail:
  host: smtp.naver.com
  smtp:
    socketFactory:
      class: javax.net.ssl.SSLSocketFactory
      fallback: 'false'
      port: '465'
    starttls:
      required: 'true'
      enable: 'true'
    port: '465'
    auth: 'true'

AdminMail:
  password: apdlvmf1dlek
  id: kjh950601


#spring:
#  mail:
#    host: smtp.naver.com
#    port: 465
#    username: kjh950601
#    password: apdlvmf1dlek
#    properties:
#      mail:
#        smtp:
#          auth: true
#          ssl:
#            enable: true