server:
  port: 9001

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/cosmost_db
    password: '1234'

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: false

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    hiddenmethod:
      filter:
        enabled: 'true'

  profiles:
    include: email, localredis

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error

jwt:
  tokenValidTime: 18000000000000
  secret: COS-MOST-TEAM-SECRET-KEY