spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/cosmost_db
    password: '1234'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: false

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher

#  profiles:
#    include: oauth

jwt:
  tokenValidTime: 1800000
  secret: COS-MOST-TEAM-SECRET-KEY